### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [IBM/ibm-cos-sdk-python-s3transfer#1]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by barry-hueston** [comment]
Internal reference: CSAFE-54266

**Comment by barry-hueston** [comment]
@cclauss this issue has been resolved in the latest release of the SDKs, version 2.5.0.  Please review and let us know if this issue can be closed.

**Comment by cclauss** [comment]
Removing __.travis.yml__ fixed this issue.
