### ISSUE TITLE
Can not be used in python3

### ISSUE THREAD

**Issue by hunter1028** [IBM/ibm-cos-sdk-python-s3transfer#3]
How this can be used in python3

------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "XXXX\Python\Python37\lib\site-packages\ibm_s3transfer\aspera\futures.py", line 26, in <module>
    from cos_aspera import faspmanager2
ModuleNotFoundError: No module named 'cos_aspera'
------------------------------------------------------------------------------------------------------------------it it seems that [cos_aspera]  only support for  python 2.7

**Comment by cpcunningham** [comment]
can you do  install the aspera plugin and try again
pip install cos-aspera

**Comment by barry-hueston** [comment]
@hunter1028 can you let us know if installing the Aspera plugin resolved your issue please?

**Comment by hunter1028** [comment]
@barry-hueston-IBM Thanks for your reply.
 I installed the [IBM Aspera Connect] , but did not resolve that.
Is there any other solutions. or your python is version 2?

**Comment by cpcunningham** [comment]
@hunter1028 - can you do the following

1) Install cos_aspera plugin 
   pip install cos_aspera 
   Collecting cos_aspera
   Installing collected packages: cos-aspera
   Successfully installed cos-aspera-0.1.163682

2) Verify the install
    pip freeze | grep aspera
    cos-aspera==0.1.163682

3) If 1 and 2  work - then run your test

**Comment by barry-hueston** [comment]
> @barry-hueston-IBM Thanks for your reply.
> I installed the [IBM Aspera Connect] , but did not resolve that.
> Is there any other solutions. or your python is version 2?

Hi @hunter1028 , "IBM Aspera Connect" is a separate client, which operates outside of the SDKs.  The instructions above provided by @cpcunningham should get you up and running with the COS Python SDK.

**Comment by barry-hueston** [comment]
IBM Cloud Documents:
https://cloud.ibm.com/docs/services/cloud-object-storage/basics?topic=cloud-object-storage-aspera&programming_language=python

**Comment by barry-hueston** [comment]
@hunter1028 can you let us know how you got on after the aspera lib installation please.

**Comment by hunter1028** [comment]
@cpcunningham @barry-hueston-IBM   Thanks  for your support.
I download the whl file here : https://pypi.org/project/cos-aspera/#files
 and installed cos-aspera locally successfully. 
But When I run the module , [ No module named '_faspmanager2' ]  occured .

And I do not understand [ Install cos_aspera plugin ].

**Comment by vjerch** [comment]
@hunter1028 what is your host OS?

On linux as mentioned above by @cpcunningham, installation should work for python 2 and python 3 (also if using virtual environment):

```
$ pip install cos_aspera
$ pip freeze | grep aspera

```
On Windows system, assuming you have python and pip installed (environment variables set), open command line and type:

```
> pip install cos_aspera
> pip list
```

Second command for both OS should show you package version set as 0.1.163682.

**Comment by hunter1028** [comment]
@vjerch 

Yes

OS： Windows 10,  Python 3.7.2
pip list :

cos-aspera             0.1.163682

When I run the program. Below messages occured.
------------------------------------------------------------------------------------------------------
  File "AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_faspmanager2'
------------------------------------------------------------------------------------------------------

**Comment by vjerch** [comment]
@hunter1028 I replicated your issue on my system. I first did pip install cos_aspera on 2.7.8 python through command line (it installed C:\Python278\Lib\site-packages).

I created a small script test_aspera.py and switched to Python 3.6.4 virtual environment in PyCharm.


```
from cos_aspera import faspmanager2

def main():
    faspmanager2.configureAsperaLocation('nothing')

if __name__ == "__main__":
    main()

```

PyCharm saw the reference but blow up with the same No module named: _faspmanager2.

In PyCharm on my virtual environment I switched to 3.6.4 (from 2.7.8 venv) and then again installed cos-aspera package (it was installed in C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\site-packages), script then ran normally. Can you maybe try similar steps to this and see if that resolves the issue?

**Comment by vjerch** [comment]
@hunter1028 also, cos-aspera doesn't support Python 3.7.+ versions yet

**Comment by hunter1028** [comment]
> 
> 
> @hunter1028 also, cos-aspera doesn't support Python 3.7.+ versions yet

Thank your. I will try other solutions.

**Comment by barry-hueston** [comment]
Hi @hunter1028, is there a requirement that your project uses Python 3.7? i.e. are you not in a position to use Python 3.6?

**Comment by barry-hueston** [comment]
Hi @hunter1028 , we are working on providing a solution which supports python 3.7, in the meantime, could you use Python 3.6 please.

**Comment by mathieu-holl-ibm** [comment]
@hunter1028 Aspera team is aware and has received a proposed design that would enable support for future Python versions without the need to update the SDK. 
However, there is no date to support python 3.7 as of now.

If you end up having issues using Aspera and Python 3.6 please open a new ticket. 
Will close this ticket as it relates to Python 3.7 and Aspera which is not supported.

**Comment by wbhuberIBM** [comment]
Per @mathieu-holl-ibm, closing this issue.

**Comment by bambrozio** [comment]
https://github.com/IBM/ibm-cos-sdk-python-s3transfer/issues/4
